name: Release Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  releast:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: publish a release on new versions
        uses: softprops/action-gh-release@v1
        with:
          files: |
            manifest.json
            main.js