name: Release Package

on:
  push:
    branches: ['master']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: detect new versions
        id: check-version
        uses: salsify/action-detect-and-tag-new-version@v2
      - name: publish a release on new versions
        uses: ncipollo/release-action@v1.7.3
        if: steps.check-version.outputs.tag
        with:
          tag: ${{ steps.check-version.outputs.tag }}
          artifacts: "main.js,manifest.json"
          token: ${{ secrets.GITHUB_TOKEN }}