name: Release Package

on:
  push:
    branches: ['master']

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: detect new versions
        uses: salsify/action-detect-and-tag-new-version@v2
      - name: publish a release on new versions
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            manifest.json
            main.js