name: Tag New Versions

on:
  push:
    branches: ['master']

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: detect new versions
        uses: salsify/action-detect-and-tag-new-version@v2